### ISSUE TITLE
x/sequencers: fix reduce bond if condition 

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1058]
https://github.com/dymensionxyz/dymension/blob/acd9d13935a98dd43d13affdd440a78c85f3a961/x/sequencer/keeper/msg_server_decrease_bond.go#L26-L29

https://github.com/dymensionxyz/dymension/pull/1031#discussion_r1706933044

**Comment by spoo-bar** [comment]
Addressed in https://github.com/dymensionxyz/dymension/pull/1136/files
