### ISSUE TITLE
x/sequencers: start sequencer unbonding when they are jailed

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1071]
https://github.com/dymensionxyz/dymension/blob/acd9d13935a98dd43d13affdd440a78c85f3a961/x/sequencer/keeper/slashing.go#L100

Needs to be changed

**Comment by mtsitrin** [comment]
why is that? I think it was discussed and decided to be set as `unbonded`

**Comment by danwt** [comment]
> and decided to be set as unbonded

Ok, so we need to refund any remaining tokens instead?

https://dymensionworkspace.slack.com/archives/C07BRL21528/p1723192311238619?thread_ts=1723130747.352479&cid=C07BRL21528

> IMO on jailing, his tokens should be either slashed or starts unbonding

🤔
