### ISSUE TITLE
Panic running locally (app.txEncoder is nil)

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1159]
I rebooted a local hub instance and saw this
`ERR panic recovered in PrepareProposal height=344 module=server panic="runtime error: invalid memory address or nil pointer dereference"`
I lost the rest of the logs unfortunately

294d5bcdd238567ca3e87e913f1cc669198a43cd

**Comment by mtsitrin** [comment]
it caused 

it caused by this call
```
func (app *BaseApp) PrepareProposalVerifyTx(tx sdk.Tx) ([]byte, error) {
	bz, err := app.txEncoder(tx)
	if err != nil {
		return nil, err
	}

	_, _, _, _, err = app.runTx(runTxPrepareProposal, bz) //nolint:dogsled
	if err != nil {
		return nil, err
	}

	return bz, nil
}
```

as `app.txEncoder` is nil.

probably needs to be set by

```
// SetTxEncoder sets the TxEncoder if it wasn't provided in the BaseApp constructor.
func (app *BaseApp) SetTxEncoder(txEncoder sdk.TxEncoder) {
	app.txEncoder = txEncoder
}
```
