### ISSUE TITLE
IRO Impl

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1164]
Implement IRO based on this ADR: https://www.notion.so/dymension/ADR-x-IRO-533f1c2f5a2345838150dd8e954c99c6?pvs=4

**Comment by mtsitrin** [comment]
### bonding curve

- [ ] implement mx^N+c bond curve
- [ ] UT

### iro module
- [ ] Plan createmint and register FUT denom
- [ ] Trade methods
- [ ] Claim method
- [ ] Taker fee
- [ ] Queries

### liquidity bootstrap
- [ ] calc last price and required bootstrap amounts
- [ ] dedicated module account per plan to account raised DYM
- [ ] Creation fee
- [ ] INCENTIVES for leftovers



### genesis transfer (IRO settlement phase)
- [ ] refactor to validate genesis transfer against IRO
- [ ] add `RollappTransfersEnabled` hook
- [ ] IRO settlement

### rollapp module
- [ ] enforce not active until `pre_launch_time`
- [ ] enforce no checksum changes when iro plan exists
