### ISSUE TITLE
Mark empty DRS version vulnerable

### ISSUE THREAD

**Issue by keruch** [dymensionxyz/dymension#1233]
Links to #1207 

Currently we support empty DRS versions due to the backward compatibility. In the future, this field will become mandatory. The upgrade plan is:
1. first support empty DrsVersion
2. wait for a while until the majority of sequencers update to the new version
3. mark empty `""` DrsVersion vulnerable
4. add `DrsVersion != ""` validation: `x/rollapp/types/message_update_state.go:ValidateBasic`
5. delete `DrsVersion == ""` conditions: `x/rollapp/keeper/msg_server_mark_vulnerable_rollapps.go:MarkVulnerableRollapps`

**Comment by danwt** [comment]
Superseded by https://github.com/dymensionxyz/dymension/issues/1414
