### ISSUE TITLE
Revised Genesis Bridge - Impl

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1250]
based on https://www.notion.so/dymension/ADR-x-Genesis-Bridge-WIP-109a4a51f86a80ba8b50db454bee04a7?pvs=4

**Comment by mtsitrin** [comment]
- [ ] Register expected `GenesisAccounts` as part of the `genesisInfo`
- [ ] Implement the genesis bridge middleware that parses `GenesisBridgeData`
- [ ] validation of GenesisInfo, nativeDenom metadata
- [ ] Implement the splitting of the transfer between IRO and genesis accounts on the Hub side⁠
