### ISSUE TITLE
Retry failed liveness events

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1261]
In x/rollapp/keeper/liveness.go:47, rollapp liveness events are handled with an ApplyFuncIfNoError wrapper, that gracefully handles error by preventing inconsistent states.
Within this error handling, however, there is no retry logic: if for whatever reason a liveness event is not handled properly, it is never retried. This because liveness events are queried from the storage at exact height, so the fact that they are kept in storage does not mean they will be retried - and this is different from how it happens for other similar parts like the unbonding events.
Recommendation
We recommend updating the liveness handling logic to either reschedule failed events at the next block, or querying for “maximum” instead of “exact” block heights.

IMO not sure it's worth retrying because why would it work next time?

But need to check anyway that full lifecycle is correct, similar to https://github.com/dymensionxyz/dymension/issues/1050

**Comment by omritoptix** [comment]
doesn't sound like MVP material to me, even if true.

**Comment by danwt** [comment]
Yeah gonna close for now. Not MVP and if it failed the first time why would it work the second time? But I will document in the code better
