### ISSUE TITLE
Slash should not burn non-dym

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1262]
In x/sequencer/keeper/unbond.go:77, the Hub logic handles the bond of jailed sequencers by burning them.
While this is working as designed if the bond is denominated only in DYM, this may not always be the case; for example, if the bond is partly made of IBC tokens, these tokens may require the burn to happen in their source chain.
Recommendation
We recommend changing the jailing logic to seize tokens in favor of a trusted treasury address instead of burning them.

**Comment by omritoptix** [comment]
min bond is a param. we can assume it's always DYM for the time being. so I'm not gonna close this issue but it's not for 3D.

**Comment by danwt** [comment]
superseded by https://github.com/dymensionxyz/dymension/issues/1328

**Comment by mtsitrin** [comment]
Sequencer bond is currently enforced to be single denom (DYM)

**Comment by danwt** [comment]
Thanks @mtsitrin , closing
