### ISSUE TITLE
IRO trade instability when soldAmt < 1 token

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#1320]
due to limits in osmomath with `X^N` calculation, we have various restrictions on trade **while `soldAmt` < 1 token:**
* can't buy less than 1 token
* can't buy using `ExactDym`

suggested solution is to set soldAmt = 1 token on creation.
* this token can't be sold, and needs to be used for liquidity
* might be alternative to the 99.99% sold limit we have (we have this limit to ensure we have tokens to create the pool at the end)

**Comment by omritoptix** [comment]
> suggested solution is to set soldAmt = 1 token on creation.

also adding we discussed charging it as a fee and putting it in the pool
