### ISSUE TITLE
Fix create-sequencer command so it can receive the new ed25519 PubKey format

### ISSUE THREAD

**Issue by ItzhakBokris** [dymensionxyz/dymension#138]

**Comment by liorzilp** [comment]
The CLI needs to support json of [cryptotypes.PubKey](http://github.com/cosmos/cosmos-sdk/codec/types) such as: 
`'{"@type": "/cosmos.crypto.secp256k1.PubKey","key": "A1PnLi9BGKzUoyJTsyq09MUvxUg+ZgcKgv1l0EE5tJXx"}'`
