### ISSUE TITLE
migration: fork related

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1415]
See https://docs.google.com/spreadsheets/d/1wGMQbrsGAwiSAmRGHbM8oDAkklH1lHqgcdxU3YsMIYw/edit?gid=394826780#gid=394826780

**Comment by mtsitrin** [comment]
what migration needed here?
`nextProposer` field on state infos?
```
Iterate through all state infos and set to be the proposer of the rollapp
```
?

**Comment by omritoptix** [comment]
from the sheet:

Add revision
Add first revision height
Add next proposer field
