### ISSUE TITLE
Set a genesis parameter for permissionless RollApp deployment

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension#142]
### Overview

Eventually there will be multiple testnets (i.e. permissioned RollApp deployment and permissionless). They will live in parallel to let developers to build on the permissionless testnet and prepare a permissioned for launch which will upgrade to a permissionless network.

### Proposal  
Recommend setting a genesis parameter that indicates if the network is permissioned and who are the administrators. Setting this parameter to false remove admins and removes permissioned constraints.

**Comment by liorzilp** [comment]
If the list of permissioned is empty, it means it is permissionless.
