### ISSUE TITLE
Invariant simulation tests using rapid

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1484]

**Comment by danwt** [comment]
Invariants: https://docs.google.com/spreadsheets/d/1uEvOizwu1RSLoUoQxdp5apVPo61QOKoQBOm4F5y0S9A/edit?usp=sharing

**Comment by danwt** [comment]
Closing in favor of https://github.com/dymensionxyz/research/issues/440

And also there is https://github.com/dymensionxyz/dymension/issues/1253 which already has a PR open for it https://github.com/dymensionxyz/dymension/pull/1532
