### ISSUE TITLE
Add missing export genesis to mainnet simulation branch

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#1505]
Currently we use [`ducnt/v3.1.0`](https://github.com/dymensionxyz/dymension/tree/ducnt/v3.1.0) as a starting point to export mainnet genesis.
2 methods are missing there in order to have a full relevant state of mainnet:

1. RollappByEIP155KeyPrefix - we currently don't import those objects
2. VFC contract - we currently don't import the existing contracts

we need to update the current branch to also export those genesis metrics.

**Comment by mtsitrin** [comment]
why u think there's issue with `RollappByEIP155KeyPrefix`?
seems it's set together with the rollapp object, implicitly from the rollappId

```

// SetRollapp set a specific rollapp in the store from its index
func (k Keeper) SetRollapp(ctx sdk.Context, rollapp types.Rollapp) {
	store := prefix.NewStore(ctx.KVStore(k.storeKey), types.KeyPrefix(types.RollappKeyPrefix))
	b := k.cdc.MustMarshal(&rollapp)
	store.Set(types.RollappKey(
		rollapp.RollappId,
	), b)

	// check if chain-id is EVM compatible. no err check as rollapp is already validated
	rollappID, _ := types.NewChainID(rollapp.RollappId)
	if !rollappID.IsEIP155() {
		return
	}

	// In case the chain id is EVM compatible, we store it by EIP155 id, to be retrievable by EIP155 id key
	store = prefix.NewStore(ctx.KVStore(k.storeKey), types.KeyPrefix(types.RollappByEIP155KeyPrefix))
	store.Set(types.RollappByEIP155Key(
		rollappID.GetEIP155ID(),
	), b)
}
```

**Comment by omritoptix** [comment]
the only things left to pull into ducnt/v3.1.0 branch is the vfc migrations from this pr: https://github.com/dymensionxyz/ethermint/pull/30#pullrequestreview-2448782922
