### ISSUE TITLE
Feature Request: sponsorship event for scoring

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#1535]
@yishay-dym asked for a sponsorship scoreboard so I need an event to listening to, to be able to index score.

Similar to beneficiary of `x/txfees.EventChargeFee` would be great
```go
	&types.EventChargeFee{
		...
		Beneficiary:        ValueFromPtr(beneficiary).String(),
		BeneficiaryRevenue: beneficiaryCoins.String(),
	}
```

**Comment by mtsitrin** [comment]
suppressed by #1545
