### ISSUE TITLE
Minor: Incomplete validation for MsgRollappFraudProposal

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1587]
Severity: Minor
In x/rollapp/types/message_fraud_proposal.go:14-32, the ValidateBasic method of the MsgRollappFraudProposal is incomplete. It does not validate fields such
24
DRAFT – NOT INTENDED TO BE SHARED
as RollappId, RollappRevision, FraudHeight, and PunishSequencerAddress to ensure they are correctly set and valid.
Without these validations, an invalid fraud proposal could be accepted for voting, run the full proposal lifecycle, only to fail during execution. This creates inefficiencies and risks undermining the governance process.
Recommendation
We recommend enhancing the Validate method to include comprehensive checks for the MsgRollappFraudProposal.

Same probably goes for slash proposal

**Comment by mtsitrin** [comment]
dup of #1558
