### ISSUE TITLE
rollapp without ibc channel created will fail to rotate to sentinel

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymension#1598]
rollapp will be dead if active sequencer unbonds without successor before ibc channel is created, since rotation to sentinel (that requires fork) will fail and it wont be possible to complete the rotation, but last batch will be already created and no more blocks will be created by active sequencer, so no possible to create channel afterwards. 
also requiring active channel to fork it will prevent upgrading rollapps with deprecated drs, or passing fraud proposals successfully.

**Comment by danwt** [comment]
seeems it was fixed by https://github.com/dymensionxyz/dymension/commit/29e5c75735d6f36a30980cd43427aaa6e5f5e2a1
