### ISSUE TITLE
Replace existing tendermint with Informal's fork

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension#181]
### Overview

The current Tendermint repo is being archived as noted [here](https://github.com/tendermint/tendermint/issues/9972) and further elaborated in this twitter thread by Informal's team [here](https://twitter.com/informalinc/status/1613580954383040512?s=20&t=p23s0rH7W7PhmW6BkOoLBw). As such we should replace the existing Tendermint with Informal's fork which will be maintained.

### To-Do

Replace existing Tendermint with Informal Tendermint [v0.34.24](https://github.com/informalsystems/tendermint/releases/tag/v0.34.24)

**Comment by mtsitrin** [comment]
replaced by #248
