### ISSUE TITLE
Replace IRC with IBC

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension#201]
### Overview
Remove references of IRC and replace with IBC. Inter-blockchain communication in Dymension ecosystem uses IBC natively. There is no need for references to IRC.

### Task

Go through the codebase and replace IRC references. What I've found:

- [ ] testing/irc_test.go -> testing/ibc_test.go

**Comment by Wholesomebruh** [comment]
Hey, I'm interested in this issue, please explain little more. Should irc be replaced with ibc everywhere alongwith proper implementation?

**Comment by shaolin-flow** [comment]
@Wholesomebruh
Closing this issue, will update requirements in the near future
