### ISSUE TITLE
Allow establishment of IBC connection without waiting for finalization

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#207]
Currently, the IBC setup phase takes a long time as each state transition on the rollapp waits for state update AND finalization period.

As the finalization period going to increase for mainnet, we need a solution for quick finality for IBC setup phase.

**Comment by liorzilp** [comment]
There is a discussion regarding it:
https://github.com/dymensionxyz/research/discussions/68

**Comment by mtsitrin** [comment]
duplicate of #233
