### ISSUE TITLE
Config SLIP-44

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension#249]
Configuring the SLIP-044 cointype to 60 (Ethereum derivation path) enables interoperability across to Ethereum ecosystems. This should be initiated with the new testnet see [here](https://github.com/evmos/evmos/blob/main/types/hdpath.go) which is set in Main.go for implementation and registered in the chain-registry [here](https://github.com/cosmos/chain-registry).

**Comment by mtsitrin** [comment]
@shaolin-flow it's a task to do for the permissionless release? it's a research topic?

**Comment by shaolin-flow** [comment]
@mtsitrin After discussing with @yishay-dym offline, we decided this is for mainnet.

**Comment by mtsitrin** [comment]
dup of #254
