### ISSUE TITLE
chain-id flag only accepts evmos-like chain-id formats

### ISSUE THREAD

**Issue by McDaan** [dymensionxyz/dymension#270]
Binary version: v1.0.0-rc1
Steps to reproduce: 
> dymd init flopflop --chain-id="froopyland-1"
> Error: invalid chain-id format: froopyland-1

Init command worked after using an Evmos-like chain-id (froopyland_9000-1).

Expected behaviour: it must accept different kind of chain-id formats.

**Comment by shaolin-flow** [comment]
Fixed thanks

**Comment by shaolin-flow** [comment]
Updated the Genesis instructions for new chain-id compatible with Ethermint `froopyland_9000-1`
