### ISSUE TITLE
Fix readme.md linting errors

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#278]

**Comment by Wholesomebruh** [comment]
@omritoptix 
![image](https://github.com/dymensionxyz/dymension/assets/109906215/b104ec9b-676d-4d38-af16-cb4b61c94063)
Check the 3rd line of code .
According to linting rules, there should be `inline HTML` element , and for this, img tag needs to be removed . If we go with this, constraint of `width=830` will be removed. Should we fix original image size to 830 and change it with present one or is there anything else we can do?

**Comment by omritoptix** [comment]
Thank you @Wholesomebruh . feel free to fix the image if helps and submit a PR.

**Comment by Wholesomebruh** [comment]
Thanks for confirming @omritoptix  . Can you please confirm the 3rd line of code in the image provided? It should be
```bash
dymd add-genesis-account "$(dymd keys show "$KEY_NAME" -a --keyring-backend test)" 100000000000udym
```
or just 
```bash
dymd add-genesis-account "$(dymd keys show "$KEY_NAME" -a --keyring-backend test)"
```

**Comment by Wholesomebruh** [comment]
@omritoptix  Please check #279

**Comment by Wholesomebruh** [comment]
Hi, close this as completed.
