### ISSUE TITLE
When querying for rollapps list the total always returns 0

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#281]
`dymd q rollapp list --node https://dymension-devnet.rpc.silknodes.io:443 -o json`

**Comment by mtsitrin** [comment]
It's the implementation of cosmos pagination
u can see that
`dymd q bank total --node https://dymension-devnet.rpc.silknodes.io:443 -o json`
acts the same

u can add the `--count-total` flag to get the total response
