### ISSUE TITLE
Bug: Wrong output of `dymd version`

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#300]
```bash
git checkout v1.0.2-beta
make install
dymd version # => v1.0.0-rc2
git branch # => * (HEAD detached at v1.0.2-beta)
```

Suggest: https://github.com/evmos/evmos/blob/main/Makefile#L4

**Comment by mtsitrin** [comment]
@VictorTrustyDev can't reproduce
are u sure about this bug? maybe u had previously installed `dymd` is some other location in your PATH?
