### ISSUE TITLE
Feature Suggestion: Register Denom Metadata for new received IBC

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#302]
I'm not sure if this is possible but here is my suggestion:

Whenever receive IBC from a roll app, automatically register the IBC to bank denom metadata.

### Why saving the bank denom metadata:
- Bank balances of whom received IBC will be messed up like this in any user interface:
  - udym: 1000.....
  - ibc/A1...: 500000000000000000000
  - ibc/B2...: 500000000000000000000
  - ibc/C3...: 500000000000000000000
  - ibc/D4...: 500000000000000000000
- RollApp users don't have to submit any request to update their denom metadata information to anywhere, like cosmos chain-registry, good UX.
- It is easier to display information about RollApp chains correctly and more accurate, good UX.

### Implementation:
There is a denom traces endpoint in ibc-go, you can query path and original denom from there, for example:
- path: transfer/channel-0
- denom: uatom # always the original denominator

Condition:
- If path longer than 2 (IBC via IBC, _like this: transfer/channel-0/transfer/channel-99_) => skip
- If path path is just two (transfer/channel-x) => process

How to get denom metadata for the IBC denom? I don't know, your solution.
But we can alter the `MsgCreateRollapp` to submit theire bank denom metadata during registration. The field will not be persisted to x/rollapp state, it just for input params to call to x/bank to save the metadata.

Backward compatible:
- Add a new message `MsgRegisterRollappDenomMetadata` for previously registered chains to register their denom metadata.
- Do migration to add a new field `submitted_denom_metadata = false` to previous state. This is the field where you will know if the RollApp has submitted their denom metadata or not.

**Comment by mtsitrin** [comment]
@VictorTrustyDev is this the wanted metadata to be stored on the hub?
example of uRAX token sent from a rollapp to the hub

```
{
  "metadatas": [
    {
      "description": "auto-generated metadata for ibc/0FF76C11E5321AFB1B84B60C7FD6B24F704FC2FC8D8C10D2A111579F6559D3DD from rollapp myrollapp_1234-1",
      "denom_units": [
        {
          "denom": "uRAX",
          "exponent": 0,
          "aliases": []
        },
        {
          "denom": "RAX",
          "exponent": 18,
          "aliases": []
        }
      ],
      "base": "ibc/0FF76C11E5321AFB1B84B60C7FD6B24F704FC2FC8D8C10D2A111579F6559D3DD",
      "display": "RAX",
      "name": "RAX",
      "symbol": "RAX",
      "uri": "",
      "uri_hash": ""
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```

are the `denom_units` correct from the explorer perspective?

**Comment by VictorTrustyDev** [comment]
```json
{
  "description": "auto-generated metadata for ibc/0FF76C11E5321AFB1B84B60C7FD6B24F704FC2FC8D8C10D2A111579F6559D3DD from rollapp myrollapp_1234-1",
  "denom_units": [
    {
      // denom unit exponent 0 must be the same as base
      "denom": "ibc/0FF76C11E5321AFB1B84B60C7FD6B24F704FC2FC8D8C10D2A111579F6559D3DD",
      "exponent": 0,
      "aliases": ["urax"]
    },
    {
      "denom": "RAX",
      "exponent": 18,
      "aliases": []
    }
  ],
  "base": "ibc/0FF76C11E5321AFB1B84B60C7FD6B24F704FC2FC8D8C10D2A111579F6559D3DD",
  "display": "RAX",
  "name": "RAX",
  "symbol": "RAX"
}
```
- Denom unit exponent 0 must be the same as base
- I would suggest naming convension for base denom (minimum denom) should be all lowercase following convension of famous chains, what I mean is `uRAX` => `urax`. It is the denom which applications working with, by leaving it complex, it would lead to un-expected behaviors and head-dache in the future.
