### ISSUE TITLE
Panic on Gov EVM param-change 

### ISSUE THREAD

**Issue by shaolin-flow** [dymensionxyz/dymension#307]
On Gov submission returning this error: recovered: parameter enable_call not registered. I want to note that this was sent with submit-legacy-proposal with "@type": "/cosmos.params.v1beta1.ParameterChangeProposal". 

https://explorer.silknodes.io/dymension/tx/AFF5819B3BBB591C241CB9DB0E21CD376C278381B71FB1F286C9876061D62663

**Comment by mtsitrin** [comment]
@shaolin-flow pls attach the proposal json

**Comment by mtsitrin** [comment]
`dymd tx gov submit-legacy-proposal param-change evm-proposal.json --from=dym1n897cazzpr7vnxmlhmk5vrpnvr84yfjepg2ywl --keyring-backend test --broadcast-mode block -y --node=[https://froopyland.rpc.silknodes.io:443](https://froopyland.rpc.silknodes.io/) --fees=5000000udym`

**Comment by mtsitrin** [comment]
The correct key to use in the proposal is
`EnableCall`

it should work
