### ISSUE TITLE
IBC middleware to pass token metadata to the rollapps

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#320]
When passing new tokens to the rollapps, we want the rollapp to have the token metadata for this token.

As the hub might have this data for the different tokens routed through, he can attach it to the transferred IBC tokens

This feature should be tested with the EVM rollapp automatic ERC20 conversion, as we expect the metatada to be reflected in the token's ERC20 SC

**Comment by omritoptix** [comment]
As discussed, this will need to be transferred to the RA upon gov proposal passed of denom-metadata (#639) using IBC.
