### ISSUE TITLE
Add ability to block access to all rollapp related modules 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#350]
Currently we have the ability to define only permissioned addresses for rollapp creation. 
The goal of this task is to have the ability to block any potential attack vector by user interaction with those modules until we run rollapps on mainnet. 
Maybe the current safe guards are enough. needs to be doubled check.

**Comment by mtsitrin** [comment]
as I see it:

option 1: add global enable/disable parameter flag for the rollapp module

option 2: use the current whitelist implementation.
initially start with _inactive_ address, which means rollapps can't be created.
when we'll want to enable it, we'll have a gov proposal to remove the restriction (permissionless deployers) or set actual permissioned address

**Comment by omritoptix** [comment]
Both solutions are fine IMO we just need to make sure that no state of the rollapp/sequencer modules and no txs can be sent. 

with option 1 it's more hermatic.
With option 2 we need to count on the fact that by having this also all other interactions are irrelevant.

**Comment by mtsitrin** [comment]
I'll add a param, more elegent
