### ISSUE TITLE
Dymension Froopyland RPC client Error

### ISSUE THREAD

**Issue by swlandofficial** [dymensionxyz/dymension#400]
![Ekran Alıntısı](https://github.com/dymensionxyz/dymension/assets/139103805/2774d224-5dbf-4e4f-a52f-68e1d478440a)
Dymension Froopyland RPC client was unable to broadcast the transaction, please try again later
Dymension Froopyland RPC client was unable to calculate fee, please try again later

my adress
dym1mt0pnu539v4pjltm92sz6gdt39k9eumwgh5uge
my discord
softwareland

**Comment by omritoptix** [comment]
hi @swlandofficial . has to do with the full node out of sync. our rpc provider is handling it currently.

**Comment by omritoptix** [comment]
gonna close it. feel free to open if it persists.
