### ISSUE TITLE
generic tx fees

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#438]
txfees module will have the follwing logic:

- will replace original cosmos-sdk's `DeductFee` handler, with 2 handler - `MempoolCheck` and `DeductFee`

- Will swap and burn all tokens in it's balance on epoch start

- Will manage accepted fees by hooking to the `pool creation` hook

----
----
----

- [ ] ante handler to accept fees
- [ ] pool creation hook to facilitate the allowed denoms
- [ ] swap and burn on epoch
- [ ] add param to epoch identifier and burn/distribute

**Comment by mtsitrin** [comment]
Few notes regarding the difference between our/osmosis/ethermint/cosmos implementations:


logic separated into two components

1. mempoolChecker - checks that the fee is sufficient
2. feeDeducter - deducts the supplied fee


**In Cosmos:**
- mempool fees checked on `ctx.IsCheckTx()` only
- all fees deducted sent for Distribution

**In Ethermint:**
- same dedcutFee as in cosmos - all fees sent for Distribution
- uses custom `DynamicFeeChecker` following the EIP-1559

**In Osmosis:**
- custom mempool checker
- - runs always, not only on `checkTx`
- - have additional gas checks:
- - - ` maximum gas per tx`
- - - `HighGasTxThreshold` - gas threshold, which above it uses discounted gas price



For dymension:
* mempool check on `checkTx()` with no additional gas limit checks
* FeeDeducter similar to osmosis - DYM goes to distribution, non-DYM to `txfee` to be burned

@omritoptix @shaolin-flow WDYT
