### ISSUE TITLE
Portal wallet different on mainnet since firebase change

### ISSUE THREAD

**Issue by Chuuuqs** [dymensionxyz/dymension#555]
Hello, I have a major problem. I logged out of my dymension portal and tried logging in this morning. I noticed you recently changed the firebase used from testnet (dymension-3f01e to dymension-mainnet) and now anytime I login my portal wallet it gives me a different wallet instead of the one I've been using since testnet where my mainnet DYM is.

I used the Google option when creating, when I login to froopyland testnet it shows my correct wallet but when I switch to the mainnet with same credentials it gives me a different one.

**Comment by Chuuuqs** [comment]
How about you try it yourself, try logining in with Google on devnet and then try it with the same key and google account on portal mainnet.
This issue started when the domain was changed before it was just portal.dymension then it became devnet.dymension so the old firebase stayed with the devnet and didn't migrate to the mainnet and so whenever it calls it, it's the new one that comes. That's how it appears to me

**Comment by omritoptix** [comment]
Thank you for raising this issue. please respond here with your TG handle and team member will reach out to resolve it.

**Comment by Chuuuqs** [comment]
Goodness thanks for replying.

TG: @ChuuqsKing

Thanks again!

**Comment by Chuuuqs** [comment]
TG @

> Thank you for raising this issue. please respond here with your TG handle and team member will reach out to resolve it.

TG: @ChuuqsKing

@omritoptix

**Comment by Chuuuqs** [comment]
Couple days now no update and about to miss the voting window.

**Comment by omritoptix** [comment]
will contact you soon. thanks for your patience.

**Comment by nzWgFPSvByEkHikJzbnzUVfo** [comment]
Hi, i have strictly the same issue.
Could you help me too? 

Here is my telegram @elli336d

Thanks a lot !

**Comment by ktronixxxx** [comment]
Hi, i'm having the exact same issue, logged in using the pin that I created b4 but it's giving me a diff wallet.. Please advice?
