### ISSUE TITLE
Question: how to generate swagger?

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymension#680]
I can't find any command to generate swagger in Makefile.

TODO:
- [ ] Re-generate swagger due to [this PR](https://github.com/dymensionxyz/dymension/pull/668) updated the _(forked)_ Ethermint lib, which contains new API endpoints for querying VFBC

**Comment by omritoptix** [comment]
@trinitys7 can you help?

**Comment by trinitys7** [comment]
@VictorTrustyDev I use the [make proto-swagger-gen ](https://github.com/cosmos/cosmos-sdk/blob/5a733e81dce237fb379f6b8d9c624f1768ca03c6/Makefile#L431) scripts from cosmos-sdk. However, the scripts only generate the query.proto file from proto folder, it would lack some file from tendermint, cosmos-sdk and ibc-go. Therefore, after generating, you need to copy the api endpoints you want to  openapi.yml

**Comment by VictorTrustyDev** [comment]
So there is not a simple way to do that atm. Ok got it, tysm
