### ISSUE TITLE
authorized rollapp deployer by default breaks rollapp registration flow

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#682]
`set_authorised_deployer_account "$(dymd keys show "$KEY_NAME" -a --keyring-backend test)"
`
as mentioned by @mtsitrin , this indeed breaks compatiblity with rollapps. 
I think for now we can either:
1. change rollapp flow (maybe an overkill for now)
2. Add a question for the user if he wants to limit the rollapps withlist (similar as we have currently about pools creation)

**Comment by mtsitrin** [comment]
I've fixed it by running the `register_rollapp` command from the `local-user` account of the hub. which is the one registered as the permission address

**Comment by omritoptix** [comment]
great. closing.
