### ISSUE TITLE
finalization errors could lead to corrupted state

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#739]
As it runs in being block, it doesn't revert on error. 
We need to wrap this part in module.go in applyFuncIfNoError:

```
func (am AppModule) EndBlock(ctx sdk.Context, _ abci.RequestEndBlock) []abci.ValidatorUpdate {
	err := am.keeper.FinalizeQueue(ctx)
```

**Comment by danwt** [comment]
just fyi you can probably do 'open with github' in the IDE (command palette) to get a link easily
