### ISSUE TITLE
rollapp registration - Impl

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#747]
We need to change the rollapp registration flow based on the following [ADR](https://www.notion.so/dymension/ADR-x-Rollapp-registration-process-draft-07f3d4f2ceed4ae9ab44f609abb6b1d1?pvs=4).

We need to create issues out of it and ideally list them in this parent issue.

**Comment by omritoptix** [comment]
blocked by https://github.com/dymensionxyz/research/issues/291

**Comment by zale144** [comment]
See this ADR for an alternative solution proposal: https://www.notion.so/dymension/ADR-x-Implementation-of-RollApp-Registration-d548ea1d12ba4cf1bf2ae68fe9354332?pvs=4

**Comment by omritoptix** [comment]
closing as dup of https://github.com/dymensionxyz/dymension/issues/978
