### ISSUE TITLE
Add missing `anteHandlers` methods in `newLegacyCosmosAnteHandlerEip712`

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#755]
2 points here:

1. The `newLegacyCosmosAnteHandlerEip712` looks to handle Cosmos transactions, same as `newCosmosAnteHandler` with the only difference that legacy handler can handle transactions signed with Ledger. If they must be equivalent in everything else, probably the legacy handler should also use `ante.NewExtensionOptionsDecorator` and `delayedack.NewIBCProofHeightDecorator` (these two are used in "normal" handler but not in "legacy" one)

2. please double-check that the `ante.NewExtensionOptionsDecorator` is intended to be configured like it is now. The checker is nil and, by looking at the config structure, someone could think that it allows all extensions but it forbids any of them

**Comment by trinitys7** [comment]
@omritoptix currently, the app set ExtensionOptionChecker to [nil](https://github.com/dymensionxyz/dymension/blob/8aaca2247210ad31649e150c120ddb9efe45579d/app/app.go#L965). This will make the LegacyCosmosAnteHandlerEip712 AnteHandler get `unknown extension options` error. I don't think we should add it into LegacyCosmosAnteHandlerEip712
