### ISSUE TITLE
`RollappFinalizedStateInvariant` will break due to reverted states

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#759]
> In x/rollapp/keeper/invariants.go:241-244, the
> RollappFinalizedStateInvariant invariant ensures that the finalized states are
> Status_FINALIZED. This is problematic because the invariant does not allow
> Status_REVERTED status, which can happen when reverting a fraudulent state, as seen in
> x/rollapp/keeper/fraud_handler.go:109.
> Consequently, the RollappFinalizedStateInvariant invariant will break incorrectly
> for reverted states, triggering a chain halt

Not sure if this is actually hapenning as reverted states should be registered as reverted but need to check.

**Comment by hoangdv2429** [comment]
as @mtsitrin have explained, I think we can close this @omritoptix wdyt
