### ISSUE TITLE
test `rollappPacket` error `OnRecvPacket`

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#775]
currently we dont test the path where after finalization has arrived  for a rollappPacket, and when it's applied, an error is returned (e.g if the OnRecvPacket returned an error on `rollapp_hooks.go`).

**Comment by mtsitrin** [comment]
another scenario to test is using PFM - when applying the delayed `OnRecv` packet, the underlying layer return nil (PFM's delayed ack)

**Comment by ThanhNhann** [comment]
I think this pr cover e2e test for this issue: https://github.com/dymensionxyz/e2e-tests/pull/83

**Comment by omritoptix** [comment]
closing as this is covered by the test spec and the issue should reference it
