### ISSUE TITLE
Genesis bridge: Validate that only a subset of denoms can be created on rollapp genesis tokens

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#795]
Currently the supplier can provide each IBC denom. we should limit it to a subset to prevent any human error.

**Comment by omritoptix** [comment]
related to https://github.com/dymensionxyz/research/issues/278

**Comment by danwt** [comment]
Solved by design since the transfers now come through ibc
https://www.notion.so/dymension/ADR-x-Genesis-Bridge-Phase-2-89769aa551b5440b9ed403a101775ce1
