### ISSUE TITLE
unable to query the state infos list by rollapp

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymension#837]
after deploying a few rollapps, it seems the latest sumbitted state and latest finalized query works fine, but the state infos list for some rollapps are returning empty list

**Comment by omritoptix** [comment]
related to #829

**Comment by mtsitrin** [comment]
I'm not sure it's a good query to expose
1. we don't prune old states
2. we don't completely control states frequency and num of blocks per each.
I think this can be DoS vector.
clutter with huge states and the query DDoS


bedsides,  it's not usable interface IMO
