### ISSUE TITLE
Is dymd broken for rollapps (NIM for example)?

### ISSUE THREAD

**Issue by slawomir-pryczek** [dymensionxyz/dymension#868]
Hey Guys, i'm trying to interact with NIM rollapp using dymd. And it's a pain (maybe because of total lack of documentation on NIM side?). So the issue is "panic: invalid Bech32 prefix; expected dym, got nim". NIM addresses have nim prefix (instead of dym). Now, i'm using NIM's RPC but still dymd will expect that all the addresses have DYM prefix. Okay... after changing address prefix to dym1 - the RPC will complain it needs nim - prefixed addresses :)

What's the best way of interacting with rollapp using dymd client (like check balances, sign transactions, doing IBC, etc.)

I'm also unable to join both NIM and DYM discords and the real issue is there are so many tools in the ecosystem that i really don't know what to use to just be able to run some basic operations on NIM rollapp.

**Comment by omritoptix** [comment]
hey @slawomir-pryczek . nim should be interacted using the rollapp-evm cli (not dymd). and it should be built with the `nim` prefix. you can see the readme of the rollapp-evm repo for more details.
