### ISSUE TITLE
Add extra information to eibc order events

### ISSUE THREAD

**Issue by zale144** [dymensionxyz/dymension#873]
The eibc demand orders could use some extra information, such as the fulfiller address, block height when it was fulfilled and so on...
The reasoning is that these will be picked up by the indexer and made available for querying, which will come useful when tracking fulfilled demand orders, in particular for the funds tracking of the eibc-client.

**Comment by omritoptix** [comment]
I believe block height is not necessary as it's part of the event data anyway.
