### ISSUE TITLE
Sequencer liveness -  fails to submit batch to SL within pre-determined time - Impl

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#927]

**Comment by danwt** [comment]
Fraud?

**Comment by danwt** [comment]
https://www.notion.so/dymension/ADR-x-Sequencer-Liveness-Slash-Phase-1-5131b4d557e34f4498855831f439d218

**Comment by danwt** [comment]
- [ ] gas cost (almost) guaranteed to be refunded
        it should be checked early on if funds are less than gas cost
- [ ] calculate slash amt and jail
- [ ] burn the sequencer funds
- [ ] burn a portion of slashed funds
- [ ] transfer a portion of slashed funds
- [ ] param for funds allocation
- [ ] lastSlashedHeight state
- [ ] multi slash for multi interval elapse
- [ ] query
- [ ] tx
- [ ] instructions for frontend development are written
