### ISSUE TITLE
Rollapp Hard fork  (hub side) - Impl

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymension#937]
blocked by: https://github.com/dymensionxyz/research/issues/292

**Comment by mtsitrin** [comment]
based on the ADR: 


`x/rollapp`:
- [ ] Update the Rollapp protobuf message to include a revision number
- [ ] Modify the MsgUpdateState to include the revision value
- [ ] validate revision number in `UpdateState` handler
- [ ] Implement the `OnHardFork` hook interface in the x/rollapp module
- [ ] Implement `HardFork` handler
  - [ ]  `modifyRollappForRollback`
  - [ ] `removeStateUpdatesUntil`
  - [ ] set new sequencer

entryPoints:
- [ ] Implement governance handlers for `MsgInvalidRollappBlock`
- [ ] Implement governance handlers for `MsgDoubleSign`
- [ ] Liveness (blocked by liveness research?)
- [ ] `HardForkObsoleteDRSVersion`
- [ ] `LightClientBogusBlock`


Callbacks:
- [ ] Implement the OnHardFork hook in the LightClient module
- [ ] Implement the OnHardFork hook in the Delayed ACK module
- [ ] Update the EIBC module to handle packet deletions triggered by Delayed ACK
- [ ] `x/sequencers`??


- [ ] Deprecate and remove usage of commontypes.Status_REVERTED across multiple modules

**Comment by mtsitrin** [comment]
will need to handle https://github.com/dymensionxyz/dymension/issues/631 as well
