### ISSUE TITLE
sequencer rotation support

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymension#993]
- [x] manage activeSequencer and nextSequencer for a rollapp
- [x] manage notice_period for unbonding sequencers
- [x] emit rotate_sequencer event
- [x] expect and handle “lastBatch”
- [x] complete the sequencer rotation
- [x] #1025

phase 2:
* enforce state_update_timeout (#927  )
* enforce final_state_update_timeout (#1085 )

**Comment by danwt** [comment]
Hey @mtsitrin , I am handling 
- enforce state_update_timeout (https://github.com/dymensionxyz/dymension/issues/870 )
- enforce final_state_update_timeout

in https://github.com/dymensionxyz/dymension/pull/1009, ADR https://www.notion.so/dymension/ADR-x-Sequencer-Liveness-Slash-Phase-1-5131b4d557e34f4498855831f439d218?pvs=25

FYI

Note: with final_state_update_timeout, you just need to define the deadline, not actually check if the deadline passed or not, this will be done lazily
